-- SQL migration generated to sync database with SQLAlchemy models
ALTER TABLE equipment ALTER COLUMN id DROP DEFAULT;
ALTER TABLE equipment ALTER COLUMN is_active DROP DEFAULT;
ALTER TABLE equipment ALTER COLUMN created_at TYPE DATETIME;
CREATE INDEX ix_equipment_id ON equipment (id);
ALTER TABLE locomotives ALTER COLUMN id DROP DEFAULT;
ALTER TABLE locomotives ALTER COLUMN is_active DROP DEFAULT;
ALTER TABLE locomotives ALTER COLUMN created_at TYPE DATETIME;
CREATE INDEX ix_locomotives_id ON locomotives (id);
ALTER TABLE sections ALTER COLUMN id DROP DEFAULT;
ALTER TABLE sections ALTER COLUMN created_at TYPE DATETIME;
CREATE INDEX ix_sections_id ON sections (id);
ALTER TABLE system_settings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE system_settings ALTER COLUMN description TYPE VARCHAR(255);
ALTER TABLE system_settings ALTER COLUMN created_at TYPE DATETIME;
ALTER TABLE system_settings ALTER COLUMN updated_at TYPE DATETIME;
CREATE INDEX ix_system_settings_id ON system_settings (id);
CREATE UNIQUE INDEX ix_system_settings_key ON system_settings (key);
ALTER TABLE checksheet_templates ALTER COLUMN id DROP DEFAULT;
ALTER TABLE checksheet_templates ALTER COLUMN version SET NOT NULL;
ALTER TABLE checksheet_templates ALTER COLUMN version DROP DEFAULT;
ALTER TABLE checksheet_templates ALTER COLUMN is_active DROP DEFAULT;
ALTER TABLE checksheet_templates ALTER COLUMN created_at TYPE DATETIME;
CREATE INDEX ix_checksheet_templates_template_code ON checksheet_templates (template_code);
CREATE INDEX ix_checksheet_templates_id ON checksheet_templates (id);
ALTER TABLE section_equipment_map ALTER COLUMN id DROP DEFAULT;
ALTER TABLE section_equipment_map ALTER COLUMN is_active DROP DEFAULT;
CREATE INDEX ix_section_equipment_map_id ON section_equipment_map (id);
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN mobile TYPE VARCHAR(15);
ALTER TABLE users ALTER COLUMN is_active DROP DEFAULT;
ALTER TABLE users ALTER COLUMN created_at TYPE DATETIME;
CREATE INDEX ix_users_id ON users (id);
ALTER TABLE checksheet_header ALTER COLUMN id DROP DEFAULT;
ALTER TABLE checksheet_header ALTER COLUMN status DROP NOT NULL;
ALTER TABLE checksheet_header ALTER COLUMN status DROP DEFAULT;
ALTER TABLE checksheet_header ALTER COLUMN submitted_at TYPE DATETIME;
ALTER TABLE checksheet_header ALTER COLUMN approved_at TYPE DATETIME;
ALTER TABLE checksheet_header ALTER COLUMN rejected_at TYPE DATETIME;
ALTER TABLE checksheet_header ALTER COLUMN last_modified_at TYPE DATETIME;
ALTER TABLE checksheet_header ALTER COLUMN pdf_path TYPE VARCHAR;
ALTER TABLE checksheet_header ALTER COLUMN created_at TYPE DATETIME;
CREATE INDEX ix_checksheet_header_id ON checksheet_header (id);
ALTER TABLE otp_logs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE otp_logs ALTER COLUMN expires_at TYPE DATETIME;
ALTER TABLE otp_logs ALTER COLUMN is_verified DROP DEFAULT;
ALTER TABLE otp_logs ALTER COLUMN created_at TYPE DATETIME;
CREATE INDEX ix_otp_logs_id ON otp_logs (id);
ALTER TABLE template_fields ALTER COLUMN id DROP DEFAULT;
ALTER TABLE template_fields ALTER COLUMN required DROP DEFAULT;
ALTER TABLE template_fields ALTER COLUMN is_active DROP DEFAULT;
CREATE INDEX ix_template_fields_id ON template_fields (id);
ALTER TABLE user_sessions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_sessions ALTER COLUMN refresh_token_hash TYPE VARCHAR(255);
ALTER TABLE user_sessions ALTER COLUMN device_id TYPE VARCHAR(100);
ALTER TABLE user_sessions ALTER COLUMN created_at TYPE DATETIME;
ALTER TABLE user_sessions ALTER COLUMN last_activity TYPE DATETIME;
ALTER TABLE user_sessions ALTER COLUMN expires_at TYPE DATETIME;
ALTER TABLE user_sessions ALTER COLUMN revoked_at TYPE DATETIME;
ALTER TABLE user_sessions ALTER COLUMN revoked_reason TYPE VARCHAR(255);
CREATE INDEX ix_user_sessions_device_id ON user_sessions (device_id);
CREATE INDEX ix_user_sessions_revoked ON user_sessions (revoked);
CREATE UNIQUE INDEX ix_user_sessions_jti ON user_sessions (jti);
ALTER TABLE checksheet_value ALTER COLUMN id DROP DEFAULT;
ALTER TABLE checksheet_value ALTER COLUMN created_at TYPE DATETIME;
CREATE INDEX ix_checksheet_value_id ON checksheet_value (id);
