from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.services.validation_service import PASS, FAIL_STATUS, validate_checksheet_values


IST = ZoneInfo("Asia/Kolkata")


class PdfService:
    def __init__(self, output_dir: str | None = None):
        base_dir = Path(__file__).resolve().parent.parent.parent
        self.output_dir = Path(output_dir) if output_dir else base_dir / "storage" / "pdfs"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _format_value(self, value: Any) -> str:
        if value is None:
            return "—"
        if isinstance(value, datetime):
            return value.strftime("%Y-%m-%d %H:%M")
        return str(value)

    def _cell(self, value: Any, style: ParagraphStyle) -> Paragraph:
        # Every table cell must be a Paragraph, not a raw string - reportlab's Table does NOT
        # wrap plain strings, so any value wider than its column silently overflows into the
        # row above/below instead of wrapping, which is what caused the overlapping text.
        # Paragraph wraps automatically and the row height expands to fit, for every column count.
        text = self._format_value(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return Paragraph(text, style)

    def _build_story(
        self,
        title: str,
        metadata: dict[str, str],
        sections: list[dict[str, Any]],
        banner: str | None = None,
        extra_story: list[Any] | None = None,
    ) -> list[Any]:
        styles = getSampleStyleSheet()
        banner_style = ParagraphStyle(
            name="BannerStyle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            spaceAfter=2,
            alignment=1,
            textColor=colors.HexColor("#0f4c81"),
        )
        title_style = ParagraphStyle(
            name="TitleStyle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=24,
            spaceAfter=12,
            textColor=colors.HexColor("#0f4c81"),
        )
        section_style = ParagraphStyle(
            name="SectionStyle",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            spaceBefore=10,
            spaceAfter=6,
            textColor=colors.HexColor("#1f4e79"),
        )
        header_cell_style = ParagraphStyle(
            name="HeaderCellStyle",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#0f4c81"),
        )
        body_cell_style = ParagraphStyle(
            name="BodyCellStyle",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=9,
            leading=11,
        )
        dense_cell_style = ParagraphStyle(
            name="DenseCellStyle",
            parent=body_cell_style,
            fontSize=8,
            leading=10,
        )
        # Module 29.9: the ONLY validation-aware styling this module contains - a plain color
        # override applied wherever a caller's row_styles says to. This file never decides PASS/
        # FAIL itself (see validate_checksheet_values); it only renders whichever style a caller
        # already resolved, keeping the PDF generator free of any validation calculation.
        fail_cell_style = ParagraphStyle(
            name="FailCellStyle",
            parent=dense_cell_style,
            textColor=colors.red,
            fontName="Helvetica-Bold",
        )

        story: list[Any] = []
        if banner:
            story.append(Paragraph(banner, banner_style))
            story.append(Spacer(1, 0.05 * inch))
        story.append(Paragraph(title, title_style))
        story.append(Paragraph("Generated by BL-DCMS", styles["Italic"]))
        story.append(Spacer(1, 0.12 * inch))

        white_header_style = ParagraphStyle(name="WhiteHeaderStyle", parent=header_cell_style, textColor=colors.whitesmoke)
        metadata_rows = [[Paragraph("Field", white_header_style), Paragraph("Value", white_header_style)]]
        for key, value in metadata.items():
            metadata_rows.append([self._cell(key, body_cell_style), self._cell(value, body_cell_style)])
        metadata_table = Table(metadata_rows, colWidths=[1.8 * inch, 4.7 * inch])
        metadata_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f4c81")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ])
        )
        story.append(metadata_table)
        story.append(Spacer(1, 0.2 * inch))

        for section in sections:
            story.append(Paragraph(str(section.get("title", "Details")), section_style))
            headers = list(section.get("headers", ["Field", "Value"]))
            cell_style = dense_cell_style if len(headers) > 2 else body_cell_style
            # Optional, same length as "rows" - row_styles[i] is a {column_index: "fail"} dict
            # naming which cells in that row should render red instead of the normal style. Purely
            # a rendering instruction handed in by the caller (see generate_checksheet_pdf); this
            # function never computes PASS/FAIL itself.
            row_styles = section.get("row_styles")
            rows = [[Paragraph(str(h), header_cell_style) for h in headers]]
            for row_index, row in enumerate(section.get("rows", [])):
                overrides = (row_styles[row_index] if row_styles else None) or {}
                # Generic for any column count - a prior version only ever took row[0]/row[1],
                # silently dropping every column past the second on any >2-column table (still
                # true of every caller until this fix, e.g. the report export's 6-column table).
                # Every value is wrapped in a Paragraph (not a raw string) so long text wraps
                # within its column and the row grows to fit, instead of overflowing into the
                # row above/below.
                rows.append([
                    self._cell(v, fail_cell_style if overrides.get(col_index) == "fail" else cell_style)
                    for col_index, v in enumerate(row)
                ])

            col_widths = section.get("col_widths") or (
                [1.8 * inch, 4.7 * inch] if len(headers) == 2 else None
            )
            table = Table(rows, repeatRows=1, colWidths=col_widths)
            table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dcebf7")),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ])
            )
            story.append(table)
            story.append(Spacer(1, 0.12 * inch))

        if extra_story:
            story.extend(extra_story)

        return story

    def _render_to_bytes(
        self,
        title: str,
        metadata: dict[str, str],
        sections: list[dict[str, Any]],
        banner: str | None = None,
        extra_story: list[Any] | None = None,
    ) -> bytes:
        buffer = BytesIO()
        document = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.6 * inch, leftMargin=0.6 * inch, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
        story = self._build_story(title, metadata, sections, banner=banner, extra_story=extra_story)
        document.build(story)
        return buffer.getvalue()

    def generate_pdf(
        self,
        title: str,
        metadata: dict[str, str],
        sections: list[dict[str, Any]],
        banner: str | None = None,
        extra_story: list[Any] | None = None,
        file_name_hint: str | None = None,
    ) -> str:
        # file_name_hint lets a caller keep a stable, unique storage filename (e.g. the checksheet
        # id) independent of the document's own visible title - needed since Module 29.7 replaces
        # the checksheet PDF's displayed title with the equipment name, which is not unique across
        # checksheets and would otherwise produce colliding/ambiguous file names.
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        stem = (file_name_hint or title).lower().replace(" ", "_")
        file_name = f"{stem}_{timestamp}.pdf"
        output_path = self.output_dir / file_name
        pdf_bytes = self._render_to_bytes(title, metadata, sections, banner=banner, extra_story=extra_story)
        output_path.write_bytes(pdf_bytes)
        return str(output_path)

    def save_pdf_bytes(self, pdf_bytes: bytes, file_name_hint: str) -> str:
        """Writes an already-fully-built PDF (e.g. a client-signed PDF from the Digital Signature
        workflow, which embeds a cryptographic signature over bytes this module already rendered)
        to storage, using the same timestamped-filename convention as generate_pdf."""
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        stem = file_name_hint.lower().replace(" ", "_")
        output_path = self.output_dir / f"{stem}_{timestamp}.pdf"
        output_path.write_bytes(pdf_bytes)
        return str(output_path)

    def _format_ist_date_time(self, dt: Any) -> tuple[str, str]:
        """(date, time) formatted in IST from a stored UTC timestamp - e.g. ("09-Jul-2026",
        "03:42 PM IST"). Naive datetimes (as stored by this app) are treated as UTC, matching the
        Dashboard's identical `formatIST` convention."""
        if dt is None:
            return "—", "—"
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        ist_dt = dt.astimezone(IST)
        return ist_dt.strftime("%d-%b-%Y"), f"{ist_dt.strftime('%I:%M %p')} IST"

    def _esc(self, value: Any) -> str:
        return self._format_value(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    def _signature_block(self, technician_name: str, employee_id: str, submitted_at: Any, digital_signature: Any = None) -> list[Any]:
        # Left column: who actually filled the checksheet and when (name, employee id, and the
        # actual submission timestamp - never an approval date/time, which this PDF deliberately
        # does not show anywhere). Right column: empty "(Reserved)" placeholder until a checksheet
        # is digitally signed (Module 39), at which point it renders the real Supervisor Digital
        # Signature metadata - Name, Employee ID, Certificate Owner, Signing Date & Time,
        # Certificate Serial Number, and Signature Status, per Module 39's PDF Signing spec.
        styles = getSampleStyleSheet()
        header_style = ParagraphStyle(name="SigHeaderStyle", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=9)
        body_style = ParagraphStyle(name="SigBodyStyle", parent=styles["BodyText"], fontName="Helvetica", fontSize=9)
        reserved_style = ParagraphStyle(name="SigReservedStyle", parent=body_style, textColor=colors.grey, fontName="Helvetica-Oblique")
        signed_style = ParagraphStyle(name="SigSignedStyle", parent=body_style, textColor=colors.HexColor("#1a7f37"))

        submitted_date, submitted_time = self._format_ist_date_time(submitted_at)

        if digital_signature is not None:
            sign_date, sign_time = self._format_ist_date_time(digital_signature.signing_timestamp)
            valid_from, _ = self._format_ist_date_time(digital_signature.certificate_valid_from)
            valid_to, _ = self._format_ist_date_time(digital_signature.certificate_valid_to)
            lines = [
                "<b>Digitally Signed By</b>",
                f"Name: {self._esc(digital_signature.supervisor_name)}",
                f"Employee ID: {self._esc(digital_signature.supervisor_employee_id)}",
                f"Approval Timestamp: {sign_date} {sign_time}",
                f"Certificate Owner: {self._esc(digital_signature.certificate_subject)}",
                f"Certificate Serial Number: {self._esc(digital_signature.certificate_serial_number)}",
                f"Certificate Issuer: {self._esc(digital_signature.certificate_issuer)}",
                f"Certificate Validity: {valid_from} to {valid_to}",
                f"Signature Status: {self._esc(digital_signature.verification_status)}",
            ]
            right_cell = Paragraph("<br/>".join(lines), signed_style)
        else:
            right_cell = Paragraph("(Reserved)", reserved_style)

        table = Table(
            [
                [Paragraph("Filled By", header_style), Paragraph("Supervisor Digital Signature", header_style)],
                [Paragraph(f"Technician Name: {technician_name or '—'}", body_style), right_cell],
                [Paragraph(f"Employee ID: {employee_id or '—'}", body_style), Paragraph("", body_style)],
                [Paragraph("Submitted On", header_style), Paragraph("", body_style)],
                [Paragraph(submitted_date, body_style), Paragraph("", body_style)],
                [Paragraph(submitted_time, body_style), Paragraph("", body_style)],
            ],
            colWidths=[3.25 * inch, 3.25 * inch],
        )
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dcebf7")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("SPAN", (1, 1), (1, 5)),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ])
        )
        return [Spacer(1, 0.1 * inch), table]

    def _build_checksheet_document(
        self, header: Any, digital_signature: Any = None, status_override: str | None = None,
    ) -> tuple[str, dict[str, str], list[dict[str, Any]], str, list[Any]]:
        # digital_signature/status_override let the Digital Signature workflow (Module 39) render
        # the PDF that is ABOUT to be cryptographically signed with its final visual content
        # (Status: APPROVED, the real signature block) already in place - at that point in
        # digital_signature_v2_service.complete_signature the DigitalSignature DB row does
        # not exist yet (it is only created once signing has actually succeeded), so header's own
        # relationship/status can't be used directly. Every other caller passes neither and gets
        # the header's own current, persisted state exactly as before.
        technician_name = getattr(header.technician, "name", None) or header.technician_mobile
        employee_id = getattr(header.technician, "employee_id", None)
        if digital_signature is not None:
            supervisor_name = digital_signature.supervisor_name
        else:
            decided_by_user = getattr(header, "approved_by_user", None) or getattr(header, "rejected_by_user", None)
            supervisor_name = getattr(decided_by_user, "name", None)

        equipment_name = getattr(header.equipment, "equipment_name", None)
        equipment_code = getattr(header.equipment, "equipment_code", None)
        if equipment_name and equipment_code:
            display_title = f"{equipment_name} ({equipment_code})"
        else:
            display_title = equipment_name or f"Checksheet #{header.id}"

        section_name = getattr(header.section, "name", None)

        metadata_items: list[tuple[str, Any]] = [
            ("Section", section_name or header.section_id),
            ("Equipment", equipment_name or header.equipment_id),
            ("Locomotive Number", getattr(header.locomotive, "loco_number", None)),
            ("Locomotive Type", getattr(header.locomotive, "loco_model", None)),
            ("Technology", getattr(header.locomotive, "technology", None)),
            ("Work Type", header.work_type),
        ]

        # Hotfix: Traction Motor Number / Maintenance Type are only meaningful for M35-TM
        # checksheets - every other section leaves both columns null on the header row, which
        # previously rendered as a permanent "—" pair on every non-TM PDF. Shown only for that
        # section, and only ever from the checksheet's own submitted header data (never a
        # constant) - a M35-TM checksheet with a genuinely blank value still renders "—" here,
        # same as any other optional field elsewhere in this table.
        if section_name == "M35-TM":
            metadata_items.append(("Traction Motor Number", header.traction_motor_number))
            metadata_items.append(("Maintenance Type", header.maintenance_type))

        metadata_items += [
            ("Template", getattr(header.template, "template_name", None) or header.template_id),
            ("Technician", technician_name),
            ("Supervisor", supervisor_name),
        ]

        metadata = dict(metadata_items)

        submitted_values = [v for v in (header.values or []) if getattr(v, "field", None) and v.field.field_type != "group"]

        # Module 29.9/29.10: validated once here, against the FULL set of the equipment template's
        # own fields (via header.template.fields, not just header.values) plus whatever else the
        # checksheet has a value row for (e.g. a section common page). Deriving this purely from
        # header.values would silently drop a GROUP's own validation_rule/validation_threshold
        # metadata (Rules 3/4) whenever that group happens to have no submitted value row of its
        # own for any reason - the group carries the rule, not its leaves, so the cross-field check
        # must always be able to see it regardless of submission completeness. This PDF module only
        # ever renders the resulting PASS/FAIL, it never computes it.
        all_fields = list(header.template.fields) if header.template else []
        seen_field_ids = {f.id for f in all_fields}
        for v in (header.values or []):
            if getattr(v, "field", None) and v.field.id not in seen_field_ids:
                all_fields.append(v.field)
                seen_field_ids.add(v.field.id)
        values_by_field_id = {v.field_id: v.field_value for v in (header.values or [])}
        validation_results = validate_checksheet_values(all_fields, values_by_field_id)

        # A checksheet's values span both its own equipment template's fields AND (if the section
        # has one) a separate common-page template's fields (Module 29.5) - the original paper
        # form shows the common page's fields (Aux Serial No/Make/dates, ...) as plain header
        # info, not as numbered checking points, so they get their own section here rather than
        # being interleaved into the S.No table by (page_number, display_order) - each template
        # numbers those independently starting from 1, so a combined sort would restart mid-table.
        auxiliary_rows = sorted(
            (v for v in submitted_values if v.field.template_id != header.template_id),
            key=lambda value: (value.field.page_number, value.field.display_order),
        )
        checking_point_rows = sorted(
            (v for v in submitted_values if v.field.template_id == header.template_id),
            key=lambda value: (value.field.page_number, value.field.display_order),
        )
        sections = []
        if auxiliary_rows:
            sections.append({
                "title": "Auxiliary Information",
                "headers": ["Field", "Value"],
                "rows": [(value.field.field_label, value.field_value) for value in auxiliary_rows],
            })
        # Observation is column index 4 - marked "fail" (rendered red) wherever
        # validate_checksheet_values decided FAIL for that specific field, and left alone
        # (normal colour) for PASS or for any field the engine has no opinion on.
        checking_point_row_styles = [
            {4: "fail"} if validation_results.get(value.field_id, PASS).status == FAIL_STATUS else {}
            for value in checking_point_rows
        ]
        sections.append({
            # Column labels and Standard/Authority values match the original TMB reference
            # checksheet exactly (see Module 29.5/29.6's TMB template metadata) - both are read
            # from TemplateField.effective_standard_value/_authority_reference, never generated,
            # inheriting from the nearest ancestor group when a grouped leaf has none of its own
            # (the paper form lists Standard/Authority once per checking point, not per sub-row).
            "title": "Checking Points",
            "headers": ["Sr. No.", "Checking Point Details", "Standard", "Authority", "Observation"],
            "col_widths": [0.7 * inch, 2.7 * inch, 1.3 * inch, 1.0 * inch, 1.6 * inch],
            "row_styles": checking_point_row_styles,
            "rows": [
                (
                    value.field.display_order,
                    value.field.breadcrumb_label(),
                    value.field.effective_standard_value(),
                    value.field.effective_authority_reference(),
                    value.field_value,
                )
                for value in checking_point_rows
            ],
        })
        sections.append({
            "title": "Final Status",
            "headers": ["Field", "Value"],
            "rows": [
                ("Status", status_override or header.status),
                ("Decided By", supervisor_name),
                ("Rejection Reason", header.rejection_reason if header.status == "REJECTED" else None),
            ],
        })

        effective_signature = digital_signature if digital_signature is not None else getattr(header, "digital_signature", None)
        extra_story = self._signature_block(technician_name, employee_id, header.submitted_at, effective_signature)

        return display_title, metadata, sections, "BL – Digital Checksheet Management System", extra_story

    def generate_checksheet_pdf(self, header: Any) -> str:
        display_title, metadata, sections, banner, extra_story = self._build_checksheet_document(header)
        return self.generate_pdf(
            display_title, metadata, sections, banner=banner, extra_story=extra_story,
            file_name_hint=f"checksheet_{header.id}",
        )

    def generate_checksheet_pdf_bytes(self, header: Any, digital_signature: Any = None, status_override: str | None = None) -> bytes:
        """Renders the same checksheet document as generate_checksheet_pdf but returns raw bytes
        instead of writing to storage - used by the Digital Signature workflow (Module 39/45) to
        produce the not-yet-cryptographically-signed PDF that the Dashboard's local signer client
        hands to the Windows-side signing bridge, before the final signed bytes come back and are
        written to disk via PdfService.save_pdf_bytes. See _build_checksheet_document for what
        digital_signature/status_override are for."""
        display_title, metadata, sections, banner, extra_story = self._build_checksheet_document(header, digital_signature, status_override)
        return self._render_to_bytes(display_title, metadata, sections, banner=banner, extra_story=extra_story)

    def generate_report_pdf(self, title: str, rows: list[dict[str, Any]]) -> str:
        if not rows:
            sections = [{"title": "No data", "headers": ["Message"], "rows": [("No checksheets matched the selected filters.", "")] }]
            return self.generate_pdf(title, {"Generated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")}, sections)

        headers = list(rows[0].keys())
        sections = [{
            "title": "Filtered Checksheets",
            "headers": headers,
            "rows": [(row.get(header, "")) for header in headers for row in [row]]
        }]
        return self.generate_pdf(title, {"Generated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")}, sections)
